version: '3.8'

services:
  app:
    image: santa1234/just3lines:latest
    ports:
      - "8080:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped